config/routes.rb
Rails.application.routes.draw do
  # get 'bands/create'
  # get 'bands/destroy'
  # get 'saved_events/create'
  # get 'users/index'
  # get 'users/show'
  devise_for :users
  root to: 'events#index'
  resources :venues, only: [:create, :update]
  resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :saved_events, only: [:create, :destroy]
  end
  get 'past_events', to: 'events#index_past'
  resources :users, only: [:index, :show, :edit, :update]
  get 'users/:id/created', to: 'users#created', as: 'user_created'
  resources :url_links, only: [:create, :destroy]
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

# as a visitor I can view all events
# as a visitor I can see the venue info in the details of events
# as a user I can save an event from the index or show page and view my saved events on my profile when logged in
# as a user I can create a new event

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id, dependent: :destroy
  has_many :saved_events, dependent: :destroy
  has_many :url_links, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :city, :country, presence: true
  validates :username, length: {
    maximum: 15,
    too_long: "%{count} characters is the maximum allowed"
  }
  validates :quote, length: {
    maximum: 48,
    too_long: "%{count} characters is the maximum allowed"
  }
  mount_uploader :photo, PhotoUploader
  include PgSearch
  pg_search_scope :search_by_username_country_state_city,
    against: %i[username country state city],
    using: {
      tsearch: { prefix: true }
    }
  geocoded_by :address
  after_validation :geocode # , if: :will_save_change_to_address?

  def address
    [city, state, country].compact.join(', ')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show created]
  before_action :find_user, only: %i[show edit update created]

  def index
    @users = User.all
    params[:query].present? ? @users = User.search_by_username_country_state_city(params[:query]) : @users
  end

  def show
    saved_event_ids = @user.saved_events.map(&:event_id)
    saved_events = Event.find(saved_event_ids)
    @events = saved_events.select { |event| event.date >= Date.today }.sort_by(&:date)
    @past_saved = saved_events.select { |event| event.end_date < Date.today }.sort_by(&:end_date)
    # if !current_user.nil?
    #   saved_event_ids = current_user.saved_events.map {|event| event.event_id }
    #   @saved_events = Event.find(saved_event_ids)
    # end
  end

  def created
    @events = Event.where("creator_id = ? AND end_date >= ?", @user, Date.today).order(date: 'ASC')
    @past_created = Event.where("creator_id = ? AND end_date < ?", @user, Date.today).order(date: 'ASC')
    # if !current_user.nil?
    #   saved_event_ids = current_user.saved_events.map {|event| event.event_id }
    #   @saved_events = Event.find(saved_event_ids)
    # end
  end

  def edit
    @url_link = UrlLink.new(url: params[:url], user_id: params[:id])
  end

  def update
    if params[:url_link].present?
      @url_link = UrlLink.new(url: params[:url_link][:url], link: params[:url_link][:link], user_id: params[:id])
      @url_link.save
    end
    @user.update(user_params) if params[:user].present?
    if @user.save
      redirect_to user_path(@user), notice: "Updated profile."
    else
      render :edit, notice: "Couldn't save."
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :photo, :country, :city, :state, :quote)
  end
end

app/views/users/_profile.html.erb
<div class="profile-section">


  <div class="profile-row-avatar">
    <div class="avatar-square profile-avatar" style="
                background-image:
                url(<%= @user.photo %>);
                ">
    </div>
    <div class="quote-col">
      <h5><%= @user.quote %></h5>
    </div>
    <span>Created Events <%= @user.events.count %></span>
  </div>

  <div class="profile-row-username">
    <h3><%= @user.username %></h3>
    <% if @user == current_user %>
      <%= link_to "Edit Profile", edit_user_path(@user), style: "font-size: 14px;" %>
    <% end %>
  </div>
  <div class="profile-location-text">
    <span><i class="fas fa-map-marker"></i></span>
    <%= @user.city unless !@user.city.present? %>
    <%= ', ' + @user.state unless !@user.state.present?  %>
    <%= ' - ' + @user.country unless !@user.country.present? %>
  </div>

  <div class="url-row">
    <% @user.url_links.each do |url_link| %>
    <div class="url-list">
      <ul>
        <li>
          <p>
            <%= url_link.link %>
          </p>
          <p>
            <%= link_to url_link.url, url_link.url, target: "_blank", class: "word-wrap" %>
          </p>
        </li>
      </ul>
    </div>
    <% end %>
  </div>


</div>

app/views/users/_tabs.html.erb
<div class="tabs">
  <div class="tabs-item <%= current_class?(user_path) %>">
    <h5 ><%= link_to 'SAVED', user_path(@user) %> </h5>
  </div>
  <div class="tabs-item <%= current_class?(user_created_path) %>">
    <h5><%= link_to 'CREATED', user_created_path %></h5>
  </div>
</div>

app/views/users/created.html.erb
<%= render 'shared/tabs' %>
<%= render "users/profile" %>
<%= render "users/tabs" %>

<% if @events.count == 0 %>
  <div class="no-results-notice">
    <p>
      <% if @user == current_user %>
        You haven't added any events yet.
      <% else %>
        <%= @user.username %> hasn't added any events yet.
      <% end %>
    </p>
  </div>
<% else %>
  <%= render "events/event_card_listings" %>
  <div class="tabs mt-5">
    <div class="tabs-item active">
      <h5>PAST</h5>
    </div>
  </div>
  <% @events = @past_created %>
  <%= render "events/event_card_listings" %>
<% end %>

app/views/users/edit.html.erb
<div>
  <!-- updating all user fields -->
  <%= simple_form_for(@user, url: user_path(@user), html: { method: :patch } ) do |f| %>
  <div class="d-flex">
    <div class="avatar-square profile-avatar" style="
              background-image:
              url(<%= @user.photo %>);
              margin-right: 16px;
            ">
    </div>
    <!-- updating user table info -->
    <div class="form-label-image">
      <%= f.input :photo, label: 'Set Profile Image' %>
      <%= f.input :photo_cache, as: :hidden %>
    </div>
  </div>
    <%= f.input :username, required: false, hint: "15 characters max" %>
    <%= f.input :city,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "city" }%>
    <%= f.input :state,
                label: 'State, Province, or County',
                required: false,
                autofocus: true,
                input_html: { autocomplete: "state" }%>
    <%= f.input :country,
                as: :string,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "country" }%>
    <%= f.input :quote, label: "Quote" %>

    <!-- delete existing urls -->
    <% current_user.url_links.each do |url_link| %>
      <div class="url-list">
        <ul>
          <li>
            <p>
              <%= url_link.link %>
            </p>
            <p>
              <%= link_to url_link.url, url_link.url, target: "_blank"%>
              <%= link_to "delete", url_link_path(url_link), method: :delete, style: "margin: 4px ", class: "orange-links"  %>
            </p>


          </li>
        </ul>
      </div>
    <% end %>

    <!-- adding a new url_link -->
    <% if @user.url_links.count <= 15 %>
      <%= simple_form_for(@url_link, url: user_path(@user), html: { method: :patch }) do |f| %>
        <%= f.input :link, label: "Name of link" %>
        <%= f.input :url, label: "Url for link" %>
        <div class="form-actions">
          <%= f.submit "Submit", class: "form-control" %>
        </div>
      <% end %>
    <% end %>

  <% end %>
  <div class="devise-link-container">
    <%= link_to "Cancel", user_path(current_user) %>
  </div>
</div>

app/views/users/index.html.erb
<%= form_tag users_path, method: :get do %>
  <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search Profiles" %>
<% end %>
<%= render 'shared/tabs' %>
<% @users.each do |user| %>
  <%= link_to(user) do %>
    <div class="card">
      <!-- <div class="card-banner">
        <div class="card-banner-image">
          <h1 class="align-content-center"><#%= user.quote %></h1>
        </div>
        <div class="avatar-square avatar-large" style="
          background-image:
          url('<#%= user.photo %>');
        ">
        </div>
      </div> -->

      <div class="card-text">
        <div class="d-flex">

          <div class="avatar-square avatar-large" style="
            background-image:
            url('<%= user.photo %>');
          ">
          </div>
          <div class="card-details ml-3">
            <%= link_to(user) do %>
              <h1><%= user.username %></h1>
              <div class="card-location-row">
                <span><i class="fas fa-map-marker electric-blue"></i></span>
                <p><%= user.city %>, <%= "#{user.state}," if !user.state.nil? %> <%= user.country %></p>
              </div>
            <% end %>
          </div>

        </div>
      </div>

    </div>
  <% end %>
<% end %>

</div>

app/views/users/show.html.erb
<%= render 'shared/tabs' %>
<%= render "users/profile" %>
<%= render "users/tabs" %>
<% if @user.saved_events.count == 0 %>
  <div class="no-results-notice">
    <p>
      <% if @user == current_user %>
        You haven't saved any events yet.
      <% else %>
        <%= @user.username %> hasn't saved any events yet.
      <% end %>
    </p>
  </div>
<% else %>

  <%= render "events/event_card_listings" %>
  <div class="tabs mt-5">
    <div class="tabs-item active">
      <h5>PAST</h5>
    </div>
  </div>
  <% @events = @past_saved %>
  <%= render "events/event_card_listings" %>
<% end %>