config/routes.rb
Rails.application.routes.draw do
  # get 'bands/create'
  # get 'bands/destroy'
  # get 'saved_events/create'
  # get 'users/index'
  # get 'users/show'
  devise_for :users
  root to: 'events#index'
  resources :venues, only: [:create, :update]
  resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :saved_events, only: [:create, :destroy]
  end
  get 'past_events', to: 'events#index_past'
  resources :users, only: [:index, :show, :edit, :update]
  get 'users/:id/created', to: 'users#created', as: 'user_created'
  resources :url_links, only: [:create, :destroy]
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

# as a visitor I can view all events
# as a visitor I can see the venue info in the details of events
# as a user I can save an event from the index or show page and view my saved events on my profile when logged in
# as a user I can create a new event

app/views/shared/_event_card_listings.html.erb
<% @events.each do |event| %>
  <div class="card mt-3" style="
    background-image: linear-gradient(120deg, rgba(0,0,0,0.8), rgba(0,0,0,0.6)),
    url('<%= event.photo %>');
  ">
    <%= link_to(event) do %>
      <div class="card-text">
        <div class="d-flex">
          <div class="cal">
            <div class="cal-month">
              <p><%= event.date.strftime("%b") %></p>
            </div>
            <div class="cal-day">
              <h1><%= event.date.day %></h1>
            </div>
            <div class="cal-weekday">
              <p><%= event.date.strftime("%A") %></p>
            </div>
          </div>

          <div class="card-details">
            <h1><%= event.title %></h1>
            <p><%= event.descript_limit %></p>
            <p><%= event.date_format %> <%= "- #{event.end_date_format}" if event.end_date.nil? == false %></p>
            <p>time: <%= event.time %></p>
            <p><%= event.creator %>
            <p><%= event.venue.name %> </p>
            <p><%= event.venue.city %>
              <%= ", #{event.venue.state}" if event.venue.state.nil? == false %>
              <%= ", #{event.venue.country}" %></p>
            <p><%= event.venue.info %> </p>
            <p><%= "This event is over" if event.past %></p>

          </div>
        </div>
      </div>
    <% end %>
    <%= link_to 'save event', event_saved_events_path(event), method: :post %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
   <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to events_path, class: "navbar-brand" do %>
         <%= show_svg "pentagram-icon.svg"  %>
    <% end %>

   <!--  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarDropdown" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

    </button> -->

    <% if user_signed_in? %>
      <!-- <li class="nav-item active">
        <#%= link_to "Home", "#", class: "nav-link" %>
      </li> -->
     <!--  <li class="nav-item">
        <#%= link_to "Settings", edit_user_registration_path(current_user), class: "nav-link" %>
      </li> -->
      <ul style="list-style: none; margin-bottom: 0px;">
        <li class="nav-item dropdown">
          <!-- <#%= image_tag "", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %> -->
          <div
            class="avatar-square dropdown-toggle"
            style="background-image: url(<%= current_user.photo %>);"
            id="navbarDropdown"
            data-toggle="dropdown"
            type="button"
            aria-controls="navbarDropdown"
            aria-haspopup="true"
            aria-expanded="false" =>
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Create Event", new_event_path, class: "dropdown-item" %>
            <%= link_to "Settings", edit_user_registration_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    <% else %>
      <li class="nav-item" style="list-style: none;">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
  </div>

app/views/shared/_tabs.html.erb
<!-- Tabs -->
<div class="mt-3">
  <div class="tabs">
    <div class="tabs-item <%= current_class?(events_path) %>">
      <h5><%= link_to 'EVENTS', events_path %></h5>
    </div>
    <div class="tabs-item <%= current_class?(past_events_path) %>">
      <h5><%= link_to 'PAST', past_events_path %></h5>
    </div>
    <div class="tabs-item <%= current_class?(users_path) %>">
      <h5><%= link_to 'PROFILES', users_path %></h5>
    </div>
  </div>
 <!--  <div class="tabs-display">
    <img class="display-content" src="images/testimg.jpg" alt="">
  </div> -->
</div>