config/routes.rb
Rails.application.routes.draw do
  # get 'bands/create'
  # get 'bands/destroy'
  # get 'saved_events/create'
  # get 'users/index'
  # get 'users/show'
  devise_for :users
  root to: 'events#index'
  resources :venues, only: [:create, :update]
  resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :saved_events, only: [:create, :destroy]
  end
  get 'past_events', to: 'events#index_past'
  resources :users, only: [:index, :show, :edit, :update]
  get 'users/:id/created', to: 'users#created', as: 'user_created'
  resources :url_links, only: [:create, :destroy]
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

# as a visitor I can view all events
# as a visitor I can see the venue info in the details of events
# as a user I can save an event from the index or show page and view my saved events on my profile when logged in
# as a user I can create a new event

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :venue
  belongs_to :creator, foreign_key: "creator_id", class_name: "User", optional: true
  has_many :saved_events, dependent: :destroy
  validates :title, :date, presence: true
  validates :title, :description, case_sensitive: false
  validates :date, uniqueness: { scope: :venue }
  scope :past_events, -> { where("end_date < ?", Date.today) }
  scope :upcoming_events, -> { where("date >= ?", Date.today) }
  mount_uploader :photo, PhotoUploader
  include PgSearch
  pg_search_scope :global_search,
    against: %i[title description date],
    associated_against: {
      venue: %i[name info city state country],
      creator: [:username]
    },
    using: {
      tsearch: { prefix: true }
    }

  def date_format
    date.strftime('%a, %b %d,  %Y')
  end

  def end_date_format
    end_date&.strftime('%a, %b %d, %Y')
  end

  def location
    "#{venue.city} " + "#{venue.state} " + "- #{venue.country} - #{venue.name}"
  end

  # def latitude
  #   venue.latitude
  # end

  # def longitude
  #   venue.longitude
  # end

  def coordinates
    [venue.longitude, venue.latitude]
  end

  def to_feature
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": coordinates
      },
      "properties": {
        "event_id": id,
        "name": title,
        "venue_name": location,
        "date": date_format
      }
    }
  end

  def past
    if end_date.nil? && date < Date.today
      true
    elsif end_date && end_date < Date.today
      true
    else
      false
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: %i[show update edit destroy]
  skip_before_action :authenticate_user!, only: %i[index index_past show]

  def index
    params[:date].present? ? startdate = params[:date] : startdate = Date.today
    params[:end_date].present? ? enddate = params[:end_date] : enddate = (Date.today + 100.year)
    query = params[:query] if params[:query].present?

    if params[:query].present?
      @events = Event.where("date >= ? AND date <= ?", startdate, enddate).order(date: 'ASC')
                     .global_search(query).upcoming_events
    else
      @events = Event.where("date >= ? AND date <= ?", startdate, enddate).order(date: 'ASC').upcoming_events
    end
    # if !current_user.nil?
    #   saved_event_ids = current_user.saved_events.map {|event| event.event_id }
    #   @saved_events = Event.find(saved_event_ids)
    # end

    # @markers = @events.map do |event|
    #   {
    #     lat: event.latitude,
    #     lng: event.longitude
    #   }
    # end

   @geojson = build_geojson
  end

  def index_past
    if params[:query].present?
      @events = Event.global_search(params[:query]).past_events
    else
      @events = Event.order(date: 'ASC').past_events
    end
    # if !current_user.nil?
    #   saved_event_ids = current_user.saved_events.map {|event| event.event_id }
    #   @saved_events = Event.find(saved_event_ids)
    # end
    @geojson = build_geojson
  end

  def new
    @venue = Venue.new
    @event = Event.new
  end

  def create
    @venue = Venue.new(venue_params)
    @event = Event.new(event_params)
    @event.creator = current_user
    date_validate
    if @venue.save
      @event.venue = @venue
    else
      @event.venue = Venue.find_by(name: params[:venue][:name], city: params[:venue][:city])
    end
    if @event.save
      redirect_to event_path(@event), notice: 'Event created.'
    else
      render :new, notice: "Missing required fields."
    end
  end

  def update
    @event.update(event_params)
    date_validate
    if params[:venue][:name].present?
      @venue = Venue.new(venue_params)
      if @venue.save
        @event.venue = @venue
        @event.update(event_params)
      elsif Venue.exists?(name: params[:venue][:name], city: params[:venue][:city])
        @event.venue = Venue.find_by(name: params[:venue][:name], city: params[:venue][:city])
      else
        @event.venue
      end
    end
    if @event.save
      redirect_to event_path(@event), notice: 'Updated'
    else
      render :show, notice: "Couldn't save"
    end
  end

  def edit
    @venue = Venue.new
  end

  def destroy
    if @event.destroy
      redirect_to request.referrer, notice: "Removed #{@event.title}"
    else
      redirect_to request.referrer, notice: "Could not delete #{@event.title}"
    end
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end

  def date_validate
    if @event.date.nil? || (@event.date.instance_of?(Date) && @event.date < Date.today)
      @event.date = Date.today
    end
    if @event.end_date.nil? || (@event.end_date.instance_of?(Date) && @event.end_date < @event.date)
      @event.end_date = @event.date
    end
  end

  def build_geojson
    {
      type: "FeatureCollection",
      features: @events.map(&:to_feature)
    }
  end

  def event_params
    params.require(:event).permit(:title, :description, :date, :end_date, :time, :photo, :source)
  end

  def venue_params
    params.require(:venue).permit(:name, :country, :state, :city, :street, :info)
  end
end

app/views/events/_event_card_listings.erb
<% @events.each do |event| %>
  <div class="card" >
    <%= link_to(event) do %>

      <div class="card-banner">
        <div class="card-banner-image" style="
        background-image: linear-gradient(120deg, rgba(0,0,0,0.3), rgba(0,0,0,0.0)),
        url('<%= event.fetch_photo.present? ? event.fetch_photo : event.photo %>');"></div>
        <div class="cal">
          <div class="cal-month">
            <p><%= event.date.strftime("%b") %></p>
          </div>
          <div class="cal-day">
            <h1><%= event.date.day %></h1>
            <p><%= event.date.strftime("%A") %></p>
          </div>
        </div>
      </div>

      <div class="card-text">
          <div class="card-details">
            <div class="card-date-row">
              <span class ="card-date"><%= event.date_format %>
                <%= "- #{event.end_date_format}" if !event.end_date.nil? && event.end_date != event.date %>
              </span>
              <% if current_user  %>
                <div class="card-save-link">
                  <% saved_event_ids = current_user.saved_events.map {|event| event.event_id } %>
                  <% saved_events = Event.find(saved_event_ids)  %>
                  <!-- if event.id is present in saved_events.event_id then show saved -->

                 <% if !saved_events.map(&:id).include?(event.id) %>
                    <div class="orange-links">
                      <%= link_to 'save', event_saved_events_path(event), method: :post %>
                    </div>
                  <% else %>
                    <% saved_event = SavedEvent.find_by(user_id: current_user, event_id: event[:id]) %>
                    <div class="grey-links">
                      <%= link_to 'saved',
                        event_saved_event_path(event_id: event.id, id: saved_event.id ), method: :delete
                      %>
                    </div>
                  <% end %>
                </div>
              <% end %>

            </div>
            <%= link_to(event) do %>
              <div class="truncate-ellipsis" style>
                <h1 class="card-title"><%= event.title %></h1>
              </div>
              <div class="truncate-ellipsis card-description">
                <p class=""><%= event.description.present? ? event.description : " " %></p>
              </div>

              <div class="card-location-row ">
                <span><i class="fas fa-map-marker orange"></i></span>
                <div class="truncate-ellipsis">
                  <p ><%= event.location %></p>
                </div>
              </div>
            <% end %>

          </div>
      </div>
      <% if current_user && current_user == event.creator %>
        <div class="card-creator-row">
          <div class="orange-links">
            <%= link_to 'delete', event_path(event), method: :delete %>
          </div>
          <% if event.date >= Date.today  %>
            <div class="orange-links">
              <%= link_to 'edit', edit_event_path(event) %>
            </div>
          <% end %>
        </div>
      <% end %>

    <% end %>


  </div>
<% end %>

app/views/events/edit.html.erb
<%= render "shared/tabs" %>
<div class="page-section">
  <h2 class="">Edit Event</h2>

  <%= simple_form_for @event do |f| %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :description %>
      <div class="form-inline form-group">
        <div class="left-date">
          <label for="" class="form-control-label justify-content-start">Start Date*</label>
          <%= f.date_field :date, class: "form-control"%>
         <!-- <#%= f.input :date, as: :date, label: "start date", class: "form-control" %> -->
        </div>
        <div>
          <label for="" class="form-control-label justify-content-start">End Date</label>
          <%= f.date_field :end_date, class: "form-control" %>
        </div>
      </div>
    </div>

    <%= simple_form_for @venue do |f| %>
      <label for="" class="form-control-label label-headers" >Venue</label>
      <div class="form-inputs">
        <%= f.input :name, label: "Venue Name",error: "This venue has an event for your date already" %>
        <%= f.input :country, as: :string  %>
        <%= f.input :state %>
        <%= f.input :city %>
        <%= f.input :street %>
        <%= f.input :info %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Submit", class: "form-control form-actions", style: "border-radius: none" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="desktop-flex">
   <div class="nav-desktop-container">
    <%= form_tag events_path, method: :get, class: "" do %>
      <div class="d-flex ">
        <div class="btn btn-grey" id="filter-btn">
          Filter
        </div>
        <div class="form-group form-inputs gro">
          <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search Events" %>
        </div>
      </div>
      <div id="filter-wrap" class="">
        <div class="form-inputs ">
          <label for="" class="form-control-label">Start Date</label>
          <%= date_field_tag :date, "", class: "form-group form-control"  %>
          <label for="" class="form-control-label">End Date</label>
          <%= date_field_tag :end_date, "", class: "form-group form-control form-control-date" %>
        </div>
        <div class="form-actions">
          <%= submit_tag  "Submit", class: "form-control form-actions"%>
        </div>
      </div>
    <% end %>

    <!-- <#%= simple_form_for events_path, method: :get do |f| %>
      <div class="form-inline">
        <#%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search Events" %>
        <div>
          <#%= f.label "from", required: false %>
          <#%= f.date_field :date, class: "form-control" %>
        </div>
        <div>
          <#%= f.label "to", required: false %>
          <#%= f.date_field :end_date, class: "form-control" %>
        </div>
        <#%= f.submit "Submit", class: "form-control" %>
      </div>
    <#% end %>

     -->
    <%= render 'shared/tabs' %>

      <div
        id="map"
        style="width: 100%;"
        data-events="<%= @geojson.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>


  </div>
  <div class="listings-desktop-container">
    <%= render 'event_card_listings' %>
  </div>
</div>

app/views/events/index_past.html.erb
<div class="desktop-flex">
  <div class="nav-desktop-container">
    <%= form_tag past_events_path, method: :get, class: "" do %>
      <div class="d-flex ">
        <div class="btn btn-grey" id="filter-btn">
          Filter
        </div>
        <div class="form-group form-inputs gro">
          <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search Past Events" %>
        </div>
      </div>
      <div id="filter-wrap" class="">
        <div class="form-inputs ">
          <label for="" class="form-control-label">Start Date</label>
          <%= date_field_tag :date, "", class: "form-group form-control"  %>
          <label for="" class="form-control-label">End Date</label>
          <%= date_field_tag :end_date, "", class: "form-group form-control form-control-date" %>
        </div>
        <div class="form-actions">
          <%= submit_tag  "Submit", class: "form-control form-actions"%>
        </div>
      </div>
    <% end %>
    <%= render 'shared/tabs' %>

      <div
        id="map"
        style="width: 100%;"
        data-events="<%= @geojson.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>

  </div>
  <div class="listings-desktop-container">
    <%= render 'event_card_listings' %>
  </div>

</div>

app/views/events/new.html.erb
<%= render "shared/tabs" %>
<div class="page-section">
  <h2 class="">Create Event</h2>

  <%= simple_form_for @event do |f| %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :description %>
      <div class="form-inline form-group">
        <div class="left-date">
          <label for="" class="form-control-label justify-content-start">Start Date*</label>
          <%= f.date_field :date, class: "form-control"%>
         <!-- <#%= f.input :date, as: :date, label: "start date", class: "form-control" %> -->
        </div>
        <div>
          <label for="" class="form-control-label justify-content-start">End Date</label>
          <%= f.date_field :end_date, class: "form-control" %>
        </div>
      </div>
    </div>

    <%= simple_form_for @venue do |f| %>
      <label for="" class="form-control-label label-headers" >Venue Information</label>
      <div class="form-inputs">
        <%= f.input :name, label: "Venue Name",error: "This venue has an event for your date already" %>
        <%= f.input :street,
                    autofocus: true,
                    input_html: { autocomplete: "street" } %>
        <%= f.input :city %>
        <%= f.input :state %>
        <%= f.input :country, as: :string  %>
        <%= f.input :info %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Create Event", class: "form-control form-actions", style: "border-radius: none" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/events/show.html.erb
<%= render "shared/tabs" %>
<div class="row mt-3" style="">
  <div class="col-sm-12 col-md-4">
    <a href="<%= @event.fetch_photo.present? ? @event.fetch_photo : @event.photo %>">
    <div class="card-banner-image card-show-image" style="
        background-image: linear-gradient(120deg, rgba(0,0,0,0.0), rgba(0,0,0,0.0)),
        url('<%= @event.fetch_photo.present? ? @event.fetch_photo : @event.photo %>');">
    </div>
    </a>
  </div>


  <div class="col-sm-12 col-md-8">
    <div class="card-show-text text-center">
      <span class ="card-date"><%= @event.date_format %>
        <%= "- #{@event.end_date_format}" if !@event.end_date.nil? && @event.end_date != @event.date %>
      </span>
      <h2><%= @event.title %></h2>
      <p><%= @event.description %></p>

      <p><%= @event.venue.name %> </p>
      <p><%= @event.venue.address %> </p>
      <div class="event-credits">
        <p><%= "Posted by: @#{@event.creator.username} on #{@event.updated_at.date_format}" if @event.creator %>
        <p><%= "Originally sourced from: #{@event.source} on #{@event.updated_at.strftime('%b %d,  %Y')}" if @event.source %>

        <p><%= "Photo credit: #{@event.photo_credit.gsub('Source: ', '')}" if @event.photo_credit %></p>

      </div>
    </div>

  </div>
</div>
<div class="link-row">
  <% if current_user && current_user == @event.creator %>
        <div class="card-creator-row">
          <div class="orange-links">
            <%= link_to 'delete', event_path(@event), method: :delete %>
          </div>
          <% if event.date >= Date.today  %>
            <div class="orange-links">
              <%= link_to 'edit', edit_event_path(@event) %>
            </div>
          <% end %>
        </div>
      <% end %>
</div>